# Generated by Django 3.0.4 on 2020-11-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20201106_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='experience_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
