# Generated by Django 3.0.4 on 2020-11-08 16:04

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20201108_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='environment',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
