# Generated by Django 3.0.4 on 2020-11-11 20:13

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20201111_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='environment',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='focus_arias',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='functional_skills',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='technical_skills',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
