# Generated by Django 3.0.4 on 2020-11-13 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20201111_2113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='focus_arias',
            new_name='focus_ares',
        ),
    ]
