# Generated by Django 3.0.4 on 2020-11-13 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20201113_2304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='focus_ares',
            new_name='focus_areas',
        ),
    ]
