# Generated by Django 3.0.4 on 2020-11-15 12:44

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_auto_20201113_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='job_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='tasks',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
